sonar.projectKey=LBHackney-IT_lbh-fss-public-frontend
sonar.organization=lbhackney-it
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.jsx,**/*.spec.js,**/*.test.jsx,**/*.test.js
sonar.exclusions=**/*.spec.jsx,**/*.spec.js,**/*.test.jsx,**/*.test.js,__mocks__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info